---
version: "3"

services:
  server:
    image: ubuntu:18.04
    environment:
    - RUN_LOG_LEVEL
    - RUN_POSTGRES_USER
    - RUN_POSTGRES_PASS
    - RUN_POSTGRES_DB
    - RUN_POSTGRES_HREF
    - RUN_POSTGRES_SSL
    - RUN_NATS_URL=nats://queue:4222
    volumes:
    - "./run-server:/bin/run-server"
    ports:
    - "9001:9001"
    command: /bin/run-server
  store:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    volumes:
    - "./dockerfiles/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  queue:
    image: nats
    ports:
    - "4222:4222"
    - "5222:5222"
    - "6222:6222"